### PR TITLE
Add rank component

### PR DESCRIPTION
**Pull request by adrianclay**

### CODE REVIEW

**Comment by camillavk** [comment]
Were we also meant to try and integrate the new component into the NewsItem component? Just wondering how the rank will go from low to high?

**Comment by adrianclay** [comment]
Ahh yeah, when I saw your PR I realised I should have done that.  Now just worried about the conflicts the `NewsItem` will generate.

**Comment by camillavk** [comment]
Yup, I see your point, the `NewsItem` will cause quite a few merge conflicts, but then again so will the `stories/index.js` won't it?

**Comment by rrpff** [comment]
Indeed, maybe in future we should build components isolated from each other when doing homework, so there's less opportunity for conflicts.

**Comment by rrpff** [comment]
@adrianclay - you're using 4 spaces everywhere instead of 2. Other than that, looks great!

**Pull request merged**
